travis:
  secure:
    BINSTAR_TOKEN: YcvJRpyP+2pNk3p/Cg7VozeKI8UcC+DJER3+SYOZc4/TrheVCDsvAsG5Ohy8Bc8cq2n/01meJ6MOnIAgTYX/nZCfrGQn4Ove13rYT60ZbEYY25Y91oCbMANxT1mHTHohcT6EBWhoHWaj9H5uhah+62tLYO/5cyckSL408zwekpAHFYcjGo1aNa3Jdf0yyP1lXuDfC6/hAJ/e9oaICIxViZZTeKrZAkOuSICji1QFvAzD5vV+6WmicMlWBzvbfFFQv+3FgLnwojKTAo55IWlBGGyLSm14LCZVl0RrqIm1BAYR6FoytYLA2Y1ECh/wS2wIDUfFx3PQZfsDupOnlEV7Maz021SKav5baxNw9vhv08GNJnYTDeRkCYOEsswaYJbj4L8H1K8YKf1qVzy1t5kvA2bm8oGXPEu1YUVtxJ2XzQ6Jno9VfBeEZKsWsi7l+ckdL6irkJM9wRUShI0lRExjUM8wT5L+hDJFHB8kMuaVPOzFv50pL/ElUb0zH7JBuEnNShNvqLyj50VDx6/DKfTqj2OICJHljzJry50Yp2/sCTfVTwReDW2BqIFcpHek819ke81A9wc+XQVapWBrVcv4XUU7olw/qCK2raSv1ZHODDIkxk8ZVVWP0iej/5f6TQgrftM0xjqyaTqbAQmNRM5pBc/bGBoSgmzObcEePVtpcNk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
